### PR TITLE
Spa

### PR DESCRIPTION
**Pull request by mora145**

### CODE REVIEW

**Comment by alextd** [comment]
Good, good. 

The DefInjected part doesn't have Spanish translations, though. Let's get those in before a full release.

**Comment by mora145** [comment]
Okay. I am looking to know how these terms are translated into Spanish correctly. When I'm sure, I add them.

**Comment by mora145** [comment]
Done

**Comment by alextd** [comment]
Okay, translations are in and it's on Steam too.

Taking my own branch and filenames instead of pulling +merging, but this is closed

**Pull request closed without merging**
