### PR TITLE
Added support for the Russian language

### PR DESCRIPTION
**Pull request by lukavskym**
Added support for the Russian language

### CODE REVIEW

**Comment by lukavskym** [comment]
I did not find where to translate this item, I circled it in the screenshot
изображение

**Comment by alextd** [comment]
https://github.com/alextd/RimWorld-SmartMedicine/blob/master/Defs/UnlimitedSurgeryColumnDefs.xml

**Comment by lukavskym** [comment]
I tried to do so. In file \Russian\DefInjected\SmartMedicineDefs.xml write:
`<UnlimitedSurgery.headerTip>Для операции использовать лучшее (игнорировать настройки медицины)</UnlimitedSurgery.headerTip>`
But it does not work. What am I doing wrong?

**Comment by lukavskym** [comment]
I found a bug and fixed it. Now the column header is translated

**Pull request merged**
